import { join } from "path";
import { mkdir, readdir, readFile, writeFile } from "fs/promises";

const PATTERNS_DIR = join(process.cwd(), ".claude", "claudeclaw", "patterns");
const PATTERNS_FILE = join(PATTERNS_DIR, "usage_log.json");
const SKILLS_DIR = join(process.cwd(), ".claude", "claudeclaw", "learned_skills");

interface UsageEntry {
  prompt: string;        // First 100 chars of the prompt
  source: string;        // "telegram", "chat", "heartbeat", "job"
  timestamp: string;
  keywords: string[];    // Extracted keywords
}

interface LearnedPattern {
  id: string;
  keywords: string[];
  frequency: number;
  lastSeen: string;
  suggestedName: string;
  templatePrompt: string;  // Common prompt pattern
  autoGenerated: boolean;
}

// Ensure directories exist
async function ensureDirs(): Promise<void> {
  await mkdir(PATTERNS_DIR, { recursive: true });
  await mkdir(SKILLS_DIR, { recursive: true });
}

// Extract keywords from a prompt (simple word frequency approach)
function extractKeywords(text: string): string[] {
  const stopWords = new Set(["the", "a", "an", "is", "are", "was", "were", "be", "been",
    "being", "have", "has", "had", "do", "does", "did", "will", "would", "could", "should",
    "may", "might", "can", "shall", "to", "of", "in", "for", "on", "with", "at", "by",
    "from", "as", "into", "through", "during", "before", "after", "this", "that", "these",
    "those", "it", "its", "my", "your", "his", "her", "our", "their", "what", "which",
    "who", "whom", "where", "when", "why", "how", "and", "or", "but", "not", "no",
    "的", "是", "了", "在", "我", "有", "和", "就", "不", "人", "都", "一", "个",
    "上", "也", "很", "到", "说", "要", "去", "你", "会", "着", "没有", "看", "好",
    "自己", "这", "他", "她", "它", "们", "那", "里", "让", "给", "把", "被"]);

  return text.toLowerCase()
    .replace(/[^\w\u4e00-\u9fff]+/g, " ")
    .split(/\s+/)
    .filter(w => w.length > 2 && !stopWords.has(w))
    .slice(0, 10);
}

// Log a usage entry
export async function logUsage(prompt: string, source: string): Promise<void> {
  await ensureDirs();

  let log: UsageEntry[] = [];
  try {
    log = JSON.parse(await readFile(PATTERNS_FILE, "utf-8"));
  } catch {}

  const entry: UsageEntry = {
    prompt: prompt.slice(0, 100),
    source,
    timestamp: new Date().toISOString(),
    keywords: extractKeywords(prompt),
  };

  log.push(entry);
  // Keep last 500 entries
  if (log.length > 500) log = log.slice(-500);

  await writeFile(PATTERNS_FILE, JSON.stringify(log, null, 2));
}

// Detect patterns from usage log
// Returns patterns that appear 3+ times
export async function detectPatterns(): Promise<LearnedPattern[]> {
  await ensureDirs();

  let log: UsageEntry[] = [];
  try {
    log = JSON.parse(await readFile(PATTERNS_FILE, "utf-8"));
  } catch {
    return [];
  }

  // Group by keyword combinations (using 2-keyword pairs)
  const pairCounts: Map<string, { count: number; prompts: string[]; lastSeen: string; keywords: string[] }> = new Map();

  for (const entry of log) {
    const kws = entry.keywords;
    // Generate pairs
    for (let i = 0; i < kws.length; i++) {
      for (let j = i + 1; j < kws.length; j++) {
        const pair = [kws[i], kws[j]].sort().join("+");
        const existing = pairCounts.get(pair);
        if (existing) {
          existing.count++;
          existing.prompts.push(entry.prompt);
          existing.lastSeen = entry.timestamp;
        } else {
          pairCounts.set(pair, {
            count: 1,
            prompts: [entry.prompt],
            lastSeen: entry.timestamp,
            keywords: [kws[i], kws[j]],
          });
        }
      }
    }
  }

  // Filter patterns with 3+ occurrences
  const patterns: LearnedPattern[] = [];
  for (const [id, data] of pairCounts) {
    if (data.count >= 3) {
      // Find common prompt prefix
      const commonPrefix = findCommonPrefix(data.prompts);
      patterns.push({
        id,
        keywords: data.keywords,
        frequency: data.count,
        lastSeen: data.lastSeen,
        suggestedName: data.keywords.join("_"),
        templatePrompt: commonPrefix || data.prompts[0],
        autoGenerated: false,
      });
    }
  }

  return patterns.sort((a, b) => b.frequency - a.frequency).slice(0, 20);
}

function findCommonPrefix(strings: string[]): string {
  if (strings.length === 0) return "";
  if (strings.length === 1) return strings[0];
  let prefix = strings[0];
  for (let i = 1; i < strings.length; i++) {
    while (!strings[i].startsWith(prefix) && prefix.length > 0) {
      prefix = prefix.slice(0, -1);
    }
  }
  return prefix.trim();
}

// Generate a skill file from a detected pattern
export async function generateSkill(pattern: LearnedPattern): Promise<string> {
  await ensureDirs();

  const skillName = pattern.suggestedName.replace(/[^a-zA-Z0-9_\u4e00-\u9fff]/g, "_");
  const skillPath = join(SKILLS_DIR, `${skillName}.md`);

  const content = `---
name: ${skillName}
description: 自动学习的技能 - 关键词: ${pattern.keywords.join(", ")}
type: learned
frequency: ${pattern.frequency}
learned_at: ${new Date().toISOString()}
---

# ${skillName}

基于使用频率自动生成的技能模板。

## 模板提示词

${pattern.templatePrompt}

## 使用关键词

${pattern.keywords.map(k => `- ${k}`).join("\n")}
`;

  await writeFile(skillPath, content);
  pattern.autoGenerated = true;
  return skillPath;
}

// List all learned skills
export async function listLearnedSkills(): Promise<Array<{ name: string; description: string; frequency: number }>> {
  await ensureDirs();

  const skills: Array<{ name: string; description: string; frequency: number }> = [];
  try {
    const files = (await readdir(SKILLS_DIR)).filter(f => f.endsWith(".md"));
    for (const f of files) {
      try {
        const content = await readFile(join(SKILLS_DIR, f), "utf-8");
        const nameMatch = content.match(/^name:\s*(.+)$/m);
        const descMatch = content.match(/^description:\s*(.+)$/m);
        const freqMatch = content.match(/^frequency:\s*(\d+)$/m);
        skills.push({
          name: nameMatch ? nameMatch[1] : f.replace(".md", ""),
          description: descMatch ? descMatch[1] : "",
          frequency: freqMatch ? parseInt(freqMatch[1]) : 0,
        });
      } catch {}
    }
  } catch {}

  return skills;
}

// Get usage stats
export async function getUsageStats(): Promise<{
  totalEntries: number;
  topKeywords: Array<{ keyword: string; count: number }>;
  sourceBreakdown: Record<string, number>;
  patternsDetected: number;
}> {
  await ensureDirs();

  let log: UsageEntry[] = [];
  try {
    log = JSON.parse(await readFile(PATTERNS_FILE, "utf-8"));
  } catch {}

  // Count keywords
  const kwCounts: Map<string, number> = new Map();
  const sourceCounts: Record<string, number> = {};

  for (const entry of log) {
    for (const kw of entry.keywords) {
      kwCounts.set(kw, (kwCounts.get(kw) || 0) + 1);
    }
    sourceCounts[entry.source] = (sourceCounts[entry.source] || 0) + 1;
  }

  const topKeywords = [...kwCounts.entries()]
    .sort((a, b) => b[1] - a[1])
    .slice(0, 20)
    .map(([keyword, count]) => ({ keyword, count }));

  const patterns = await detectPatterns();

  return {
    totalEntries: log.length,
    topKeywords,
    sourceBreakdown: sourceCounts,
    patternsDetected: patterns.length,
  };
}
